/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SalesTeamRouteImport } from './routes/sales-team'
import { Route as SalesGrindRouteImport } from './routes/sales-grind'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as EngineRoomRouteImport } from './routes/engine-room'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTeamRoute = SalesTeamRouteImport.update({
  id: '/sales-team',
  path: '/sales-team',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesGrindRoute = SalesGrindRouteImport.update({
  id: '/sales-grind',
  path: '/sales-grind',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoomRoute = EngineRoomRouteImport.update({
  id: '/engine-room',
  path: '/engine-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/engine-room': typeof EngineRoomRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/pipeline': typeof PipelineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sales-grind': typeof SalesGrindRoute
  '/sales-team': typeof SalesTeamRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/engine-room': typeof EngineRoomRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/pipeline': typeof PipelineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sales-grind': typeof SalesGrindRoute
  '/sales-team': typeof SalesTeamRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/engine-room': typeof EngineRoomRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/pipeline': typeof PipelineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sales-grind': typeof SalesGrindRoute
  '/sales-team': typeof SalesTeamRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/clients'
    | '/engine-room'
    | '/leads'
    | '/login'
    | '/notes'
    | '/pipeline'
    | '/reset-password'
    | '/resources'
    | '/sales-grind'
    | '/sales-team'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/clients'
    | '/engine-room'
    | '/leads'
    | '/login'
    | '/notes'
    | '/pipeline'
    | '/reset-password'
    | '/resources'
    | '/sales-grind'
    | '/sales-team'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/clients'
    | '/engine-room'
    | '/leads'
    | '/login'
    | '/notes'
    | '/pipeline'
    | '/reset-password'
    | '/resources'
    | '/sales-grind'
    | '/sales-team'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  EngineRoomRoute: typeof EngineRoomRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PipelineRoute: typeof PipelineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SalesGrindRoute: typeof SalesGrindRoute
  SalesTeamRoute: typeof SalesTeamRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-team': {
      id: '/sales-team'
      path: '/sales-team'
      fullPath: '/sales-team'
      preLoaderRoute: typeof SalesTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-grind': {
      id: '/sales-grind'
      path: '/sales-grind'
      fullPath: '/sales-grind'
      preLoaderRoute: typeof SalesGrindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-room': {
      id: '/engine-room'
      path: '/engine-room'
      fullPath: '/engine-room'
      preLoaderRoute: typeof EngineRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  EngineRoomRoute: EngineRoomRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PipelineRoute: PipelineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SalesGrindRoute: SalesGrindRoute,
  SalesTeamRoute: SalesTeamRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
